# Generated by Django 6.0.1 on 2026-02-19 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('total_trades', models.IntegerField(default=0)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_risk_reward', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_win', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_pair', models.CharField(max_length=6)),
                ('buy_sell', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('lot_size', models.FloatField()),
                ('trading_session', models.CharField(blank=True, choices=[('ASIA', 'Asian'), ('LONDON', 'London'), ('NY', 'New York')], max_length=10)),
                ('trade_date', models.DateField()),
                ('reflection', models.TextField(blank=True)),
                ('profit_loss', models.FloatField(default=0)),
                ('pips', models.FloatField(default=0)),
                ('risk_reward', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trade_date', '-created_at'],
            },
        ),
    ]
