# Generated by Django 6.0.1 on 2026-02-26 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_analyticssnapshot_user_alter_strategy_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name_plural': 'Strategies'},
        ),
        migrations.AddField(
            model_name='trade',
            name='commission',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trade',
            name='is_winner',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='outcome',
            field=models.CharField(blank=True, choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('BE', 'Breakeven')], editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='risk_amount',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='strategies',
            field=models.ManyToManyField(blank=True, related_name='trades', to='trades.strategy'),
        ),
        migrations.AddField(
            model_name='trade',
            name='swap',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='lot_size',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='market_pair',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pips',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit_loss',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='risk_reward',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_date',
            field=models.DateField(db_index=True),
        ),
        migrations.DeleteModel(
            name='AnalyticsSnapshot',
        ),
    ]
