# Generated by Django 6.0.1 on 2026-02-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_alter_strategy_options_trade_commission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='swap',
            new_name='swap_fees',
        ),
    ]
