# Generated by Django 6.0.1 on 2026-02-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_rename_swap_trade_swap_fees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={},
        ),
        migrations.AddField(
            model_name='trade',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='trade_screenshots/'),
        ),
    ]
