# Generated by Django 6.0.1 on 2026-07-22 09:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
